openapi: 3.0.3
info:
  title: Family-Flix
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/v1/cms/home:
    post:
      summary: 'Home Page Api'
      operationId: homePageApi
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n     \"status\": true,\n      \"message\": \"Home CMS data fetched successfully\",\n     \"statusCode\": \"200\",\n     \"data\": {\n         \"id\": 1,\n         \"top_back_image\": \"home/top_back.png\",\n         \"top_short_title\": \"Your All-In-One Entertainment Hub\",\n         \"top_main_title\": \"Unlimited Entertainment.At Your Fingertips.\",\n         \"top_button_text\": \"Sign Up Today\",\n         \"section1_main_image\": \"home/section1_main.png\",\n         \"section1_back_image\": \"home/section1_back.png\",\n         \"section2_back_image\": \"home/section2_back.png\",\n         \"section2_main_image\": \"home/section2_main.png\",\n         \"section2_title\": \"Everything You Love.All In One Place.\",\n         \"section2_description\": \"Our platform seamlessly integrates content from top streaming platforms like Netflix, Hulu, Disney, and more. Imagine having access to all your favorite shows and movies in one place, without the hassle of switching between multiple apps.\",\n         \"section2_short_title\": \"View Our Plans And Pricing\",\n         \"section2_main_icon\": \"home/main_icon.png\",\n         \"entertainment_title\": \"Entertainment Everywhere\",\n         \"entertainment_description\": \"Enjoy The Family Flix app on your TV, mobile, and tablet. Our platform supports all your devices. Anywhere, Any Device: The Family Flix Advantage\",\n         \"section3_back_image\": \"home/section3_back.png\",\n         \"section3_main_image\": \"home/section3_main.png\",\n         \"section3_title\": \"How It Works\",\n         \"section3_video_link\": \"home/4YGx75Dq9sxjUK2dMWThhIVSrYjWo9ZPNkFieaHq.mp4\",\n         \"section4_title\": \"Unbeatable Variety\",\n         \"section4_description\": \"Blockbuster hits, binge-worthy series, and hidden gems at your fingertips. A universe of entertainment curated for you.\",\n         \"section4_back_image\": \"home/section4_back.png\",\n         \"section5_back_image\": \"home/section5_back.png\",\n         \"section5_main_title\": \"Kid's Corner\",\n         \"section5_main_description\": \"<p>A dedicated space filled with family-friendly movies and shows to keep the little ones entertained. From animated adventures to educational content, we&rsquo;ve got it all in one safe and fun place.Subscription to The Family Flix means entertainment for the whole family, so your kids can have a blast while you enjoy your favorites. Subscribe today and let the young ones embark on their own cinematic journeys!</p>\",\n         \"section5_main_image\": \"home/section5_main.png\",\n         \"plan_section_title\": \"Pricing Plans & Options.\",\n         \"plan_section_back_image\": \"home/plan_back.png\",\n         \"created_at\": \"2024-03-06T05:24:23.000000Z\",\n         \"updated_at\": \"2024-03-06T05:35:15.000000Z\"\n     },\n}"
        201:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n     \"status\": false,\n    \"message\": \"No Data Found\",\n   \"statusCode\": \"401\",\n}"
      tags:
        - Endpoints
      security: []
  /api/v1/cms/grid-section:
    post:
      summary: 'Grid Section Api'
      operationId: gridSectionApi
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n  \"status\": true,\n  \"statusCode\": 200,\n  \"top_grid\": [\n      {\n          \"id\": 1,\n          \"icon\": \"grid/grid_icon1.png\",\n          \"title\": \"Unlimited Access\",\n          \"description\": \"Dive into a vast library of movies, TV series, and exclusive content.\"\n      },\n      {\n          \"id\": 2,\n          \"icon\": \"grid/grid_icon2.png\",\n          \"title\": \"Savings Simplified\",\n          \"description\": \"Affordable plans that eliminate the need for multiple subscriptions.\"\n      },\n      {\n          \"id\": 3,\n          \"icon\": \"grid/grid_icon3.png\",\n          \"title\": \"Watch Anywhere, Anytime\",\n          \"description\": \"Enjoy your favorites on your terms - mobile, desktop, or TV.\"\n      }\n  ],\n  \"entertainment_cms\": [\n      {\n          \"id\": 1,\n          \"image\": \"entertainment/en-1.png\",\n          \"image_name\": \"On Your TV\"\n      },\n      {\n          \"id\": 2,\n          \"image\": \"entertainment/en-2.png\",\n          \"image_name\": \"Mobiles & Tablets\"\n      },\n      {\n          \"id\": 3,\n          \"image\": \"entertainment/en-3.png\",\n          \"image_name\": \"On Firestick & Firecube\"\n      }\n  ],\n  \"message\": \"Grid Section CMS data fetched successfully\""
      tags:
        - Endpoints
      security: []
  /api/v1/cms/about:
    post:
      summary: 'About Page Api'
      operationId: aboutPageApi
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: true
                  statusCode: 200
                  data:
                    id: 1
                    title: 'About Us'
                    banner_img: about/abt-bg.png
                    section1_title: 'Celebrating Your Entertainment'
                    section1_description: "Welcome to The Family Flix, where our passion lies in\r\n        crafting an exceptional entertainment experience that is\r\n        both accessible and affordable, catering to your unique\r\n        tastes. Our journey began with a simple yet ambitious\r\n        vision – to create a platform that brings together the\r\n        fragmented world of streaming services, providing you with\r\n        an easier and more cost-effective way to enjoy your\r\n        favorite movies, TV series, and more."
                    section1_img: about/section1-img.png
                    section2_title1: 'Our Commitment to You'
                    section2_description1: 'At The Family Flix, our commitment is unwavering. We strive to deliver the best possible entertainment experience, and our dedicated team is at your service with top-notch customer support 24/7. We understand the value of your time and money, and our goal is to assist you in making the most of both.'
                    section2_img2: about/section2_img2.png
                    section3_title: 'What Sets Us Apart'
                    section3_back_img: about/section3_back.png
                    section3_title1: 'Vast Content Library'
                    section3_description1: 'The Family Flix takes pride in presenting an ever-expanding content library. We embrace diversity, offering a range that includes movies, TV series, anime, web series, Korean drama, and more. Whatever your interests, we have something for everyone.'
                    section3_image1: about/section3_img1.png
                    section3_title2: 'Platform Flexibility'
                    section3_description2: 'Enjoy the flexibility of watching your favorite shows and movies on your terms. The Family Flix supports all major platforms, whether you prefer streaming on your phone, tablet, or TV. Our user-friendly app ensures a seamless experience wherever you are.'
                    section3_image2: about/section3_img2.png
                    section3_title3: 'Savings & Simplicity'
                    section3_description3: 'Simplify your entertainment budget with The Family Flix’s cost-effective solutions. Bid farewell to the hassles of managing multiple subscriptions and enjoy unbeatable value for a diverse range of content.'
                    section3_image3: about/section3_img3.png
                    created_at: '2024-03-06T05:24:23.000000Z'
                    updated_at: '2024-03-06T05:24:23.000000Z'
                  message: 'About CMS data fetched successfully'
                properties:
                  status:
                    type: boolean
                    example: true
                  statusCode:
                    type: integer
                    example: 200
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      title:
                        type: string
                        example: 'About Us'
                      banner_img:
                        type: string
                        example: about/abt-bg.png
                      section1_title:
                        type: string
                        example: 'Celebrating Your Entertainment'
                      section1_description:
                        type: string
                        example: "Welcome to The Family Flix, where our passion lies in\r\n        crafting an exceptional entertainment experience that is\r\n        both accessible and affordable, catering to your unique\r\n        tastes. Our journey began with a simple yet ambitious\r\n        vision – to create a platform that brings together the\r\n        fragmented world of streaming services, providing you with\r\n        an easier and more cost-effective way to enjoy your\r\n        favorite movies, TV series, and more."
                      section1_img:
                        type: string
                        example: about/section1-img.png
                      section2_title1:
                        type: string
                        example: 'Our Commitment to You'
                      section2_description1:
                        type: string
                        example: 'At The Family Flix, our commitment is unwavering. We strive to deliver the best possible entertainment experience, and our dedicated team is at your service with top-notch customer support 24/7. We understand the value of your time and money, and our goal is to assist you in making the most of both.'
                      section2_img2:
                        type: string
                        example: about/section2_img2.png
                      section3_title:
                        type: string
                        example: 'What Sets Us Apart'
                      section3_back_img:
                        type: string
                        example: about/section3_back.png
                      section3_title1:
                        type: string
                        example: 'Vast Content Library'
                      section3_description1:
                        type: string
                        example: 'The Family Flix takes pride in presenting an ever-expanding content library. We embrace diversity, offering a range that includes movies, TV series, anime, web series, Korean drama, and more. Whatever your interests, we have something for everyone.'
                      section3_image1:
                        type: string
                        example: about/section3_img1.png
                      section3_title2:
                        type: string
                        example: 'Platform Flexibility'
                      section3_description2:
                        type: string
                        example: 'Enjoy the flexibility of watching your favorite shows and movies on your terms. The Family Flix supports all major platforms, whether you prefer streaming on your phone, tablet, or TV. Our user-friendly app ensures a seamless experience wherever you are.'
                      section3_image2:
                        type: string
                        example: about/section3_img2.png
                      section3_title3:
                        type: string
                        example: 'Savings & Simplicity'
                      section3_description3:
                        type: string
                        example: 'Simplify your entertainment budget with The Family Flix’s cost-effective solutions. Bid farewell to the hassles of managing multiple subscriptions and enjoy unbeatable value for a diverse range of content.'
                      section3_image3:
                        type: string
                        example: about/section3_img3.png
                      created_at:
                        type: string
                        example: '2024-03-06T05:24:23.000000Z'
                      updated_at:
                        type: string
                        example: '2024-03-06T05:24:23.000000Z'
                  message:
                    type: string
                    example: 'About CMS data fetched successfully'
        201:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: false
                  statusCode: 500
                  message: 'No Data Found'
                properties:
                  status:
                    type: boolean
                    example: false
                  statusCode:
                    type: integer
                    example: 500
                  message:
                    type: string
                    example: 'No Data Found'
      tags:
        - Endpoints
      security: []
  /api/v1/cms/contact:
    post:
      summary: 'Contact Page Api'
      operationId: contactPageApi
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: true
                  statusCode: 200
                  data:
                    id: 1
                    title: Contact
                    banner_img: contact/contact-banner.png
                    background_img: contact/contact-bg.png
                    main_title: 'Connect With Us'
                    short_title: 'To learn more about how Streamit can help you, contact us.'
                    button_name: 'Contact Us'
                    map_link: 'https://maps.google.com/maps?q=Orlando%2C%20Florida&t=m&z=15&output=embed&iwloc=near'
                    created_at: '2024-03-06T05:24:23.000000Z'
                    updated_at: '2024-03-06T05:24:23.000000Z'
                  message: 'Contact CMS data fetched successfully'
                properties:
                  status:
                    type: boolean
                    example: true
                  statusCode:
                    type: integer
                    example: 200
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      title:
                        type: string
                        example: Contact
                      banner_img:
                        type: string
                        example: contact/contact-banner.png
                      background_img:
                        type: string
                        example: contact/contact-bg.png
                      main_title:
                        type: string
                        example: 'Connect With Us'
                      short_title:
                        type: string
                        example: 'To learn more about how Streamit can help you, contact us.'
                      button_name:
                        type: string
                        example: 'Contact Us'
                      map_link:
                        type: string
                        example: 'https://maps.google.com/maps?q=Orlando%2C%20Florida&t=m&z=15&output=embed&iwloc=near'
                      created_at:
                        type: string
                        example: '2024-03-06T05:24:23.000000Z'
                      updated_at:
                        type: string
                        example: '2024-03-06T05:24:23.000000Z'
                  message:
                    type: string
                    example: 'Contact CMS data fetched successfully'
        201:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: false
                  statusCode: 500
                  message: 'No Data Found'
                properties:
                  status:
                    type: boolean
                    example: false
                  statusCode:
                    type: integer
                    example: 500
                  message:
                    type: string
                    example: 'No Data Found'
      tags:
        - Endpoints
      security: []
  /api/v1/cms/pricing:
    post:
      summary: ''
      operationId: postApiV1CmsPricing
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/v1/product/unbeatable-variety:
    post:
      summary: ''
      operationId: postApiV1ProductUnbeatableVariety
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/v1/plans/show:
    post:
      summary: ''
      operationId: postApiV1PlansShow
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/v1/show/detail:
    post:
      summary: ''
      operationId: postApiV1ShowDetail
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/v1/movie/detail:
    post:
      summary: ''
      operationId: postApiV1MovieDetail
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/v1/kid/detail:
    post:
      summary: ''
      operationId: postApiV1KidDetail
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/v1/contact-us:
    post:
      summary: ''
      operationId: postApiV1ContactUs
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_name:
                  type: string
                  description: ''
                  example: impedit
                user_email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: maggio.delaney@example.com
                user_phone:
                  type: string
                  description: ''
                  example: atque
                message:
                  type: string
                  description: ''
                  example: amet
              required:
                - user_name
                - user_email
                - user_phone
                - message
      security: []
tags:
  -
    name: Endpoints
    description: ''
